### ISSUE TITLE
AGAL validation failed: Temporary register read without being written to

### ISSUE THREAD

**Issue by racingpht** [adobe/glsl2agal#11]
Hi, I just got the latest compiled swc, but encountered a compiler bug:

source: 
uniform vec4 g_ViewMatrixInvVec;
uniform mat4 g_ShadowMapMatrix;
uniform vec4 g_ParametersPS;
uniform sampler2D depth;
uniform sampler2D normal;
void main()
{
  gl_FragColor = vec4(texture2D(normal, gl_TexCoord[0].xy).g > 0.25f ? 1.f : 0.5f, 1, 0, 0);
};

compiled code:
tex ft1, v0.xyyy, fs0 <2d clamp linear nomip>
slt ft0.x, fc0.x, ft1.y
sub ft1.x, fc0.y, ft0.x
mul ft3.z, ft3.z, ft1.x
add ft3.z, ft3.z, ft0.x
sub ft2.x, fc0.y, ft0.x
sub ft1.y, fc0.y, ft2.x
mul ft3.z, ft3.z, ft1.y
mul ft1.z, fc0.z, ft2.x
add ft3.z, ft3.z, ft1.z
mov ft0.yzw, fc1.xyzz
mov ft0.x, ft3.z
mov oc, ft0

mul ft3.z, ft3.z, ft1.x has used ft3 which is undefined.

**Comment by alexmac** [comment]
Thanks for the bug report, I've fixed it and checked in new binaries, let me know if you run into other problems!
