### ISSUE TITLE
Cygwin independent windows binary

### ISSUE THREAD

**Issue by grisevg** [adobe/glsl2agal#12]
Hi, 
I'm trying to make ant job which will compile all my shaders. But binary provided, requires cygwin. I have cygwin installed, but not sure how to run in ant using cygwin libraries? is it possible? Is it possible to do cygwin independent build with all libraries included?

**Comment by grisevg** [comment]
I apologize for my silly question. A bit more googling helped me. I was just needed to add cygwin\bin to windows path.

**Comment by grisevg** [comment]
But if you could provide cygwin independent windows binary, that would really help

**Comment by alexmac** [comment]
That's a fact of life with FlasCC compiled windows apps right now, and unlikely to change in the near future. It might be possible to compile the native part of the code with Visual Studio / MingW, but the AGAL optimizer is written in AS3 so overall it probably isn't going to end up in a state you would want to use...
