### ISSUE TITLE
Fails to compile in certain scenarios when "Optimize" is enbaled

### ISSUE THREAD

**Issue by grisevg** [adobe/glsl2agal#14]
Fails to compile this piece of GLSL when "optimize" is enabled:

``` GLSL
varying vec2 TexCoords;
void main()
{
    TexCoords = gl_MultiTexCoord0.xy;
    gl_Position = gl_Vertex;
}
```

Saying: 

> Error thrown by AGAL Assembler for vertex shader:
> TypeError: Error #1009: Cannot access a property or method of a null object reference.Assembling AGAL fragment shader...

**Comment by alexmac** [comment]
thanks for the bug report! it should be fixed now

**Comment by grisevg** [comment]
Thank you!
