### ISSUE TITLE
Swizzling not working like in AGALMiniAssembler

### ISSUE THREAD

**Issue by tikotus** [adobe/glsl2agal#16]
Compiling this fragment shader:

```
uniform float myConstant;
void main(void)
{
    gl_FragColor = vec4(myConstant, 0.0, 0.0, 1.0);
}
```

results in this AGAL asm code:

```
mov ft0.yzw, fc0.xyzz
mov ft0.x, fc1.x
mov oc, ft0
```

where fc0 = [0, 0, 1, 0]

When compiling with AGALMiniAssembler, apparently 

```
mov ft0.yzw, fc0.xyzz 
```

is the same as 

```
mov ft0.y, fc0.y
mov ft0.z, fc0.z
mov ft0.w, fc0.z
```

resulting in ft0 = [myConstant, 0, 1, 1]. The expected result would have been ft0 = [myConstant, 0, 0, 1].

I found this blog where the topic is discussed: http://gonchar.me/blog/goncharposts/1466

**Comment by graysonlang** [comment]
This is a common misconception. AGAL doesn't support swizzle on the target
register. It's only a mask, so your example:

mov ft0.yzw, fc0.xyzz

Really means:

mov ft0.-yzw, fc0.xyzz

So it's equivalent to:

mov ft0.y, fc0.y

mov ft0.z, fc0.z

mov ft0.w, fc0.z

Grayson

On Jan 16, 2013, at 1:41 PM, tikotus notifications@github.com wrote:

Compiling this fragment shader:

uniform float myConstant;
void main(void)
{
    gl_FragColor = vec4(myConstant, 0.0, 0.0, 1.0);
}

results in this AGAL asm code:

mov ft0.yzw, fc0.xyzz
mov ft0.x, fc1.x
mov oc, ft0

where fc0 = [0, 0, 1, 0]

When compiling with AGALMiniAssembler, apparently

mov ft0.yzw, fc0.xyzz

is the same as

mov ft0.y, fc0.y
mov ft0.z, fc0.z
mov ft0.w, fc0.z

resulting in ft0 = [myConstant, 0, 1, 1]. The expected result would have
been ft0 = [myConstant, 0, 0, 1].

I found this blog where the topic is discussed:
http://gonchar.me/blog/goncharposts/1466

—
Reply to this email directly or view it on
GitHubhttps://github.com/adobe/glsl2agal/issues/16.

**Comment by tikotus** [comment]
So do you agree with me that glsl2agal has an issue here? As you verified, 

```
mov ft0.-yzw, fc0.xyzz
```

really is equivalent to

```
mov ft0.y, fc0.y
mov ft0.z, fc0.z
mov ft0.w, fc0.z
```

which will cause the resulting color in my case to become [?, 0, 1, 1] when [?, 0, 0, 1] would be expected. Right?

EDIT:
In my opinion, 

```
gl_FragColor = vec4(myConstant, 0.0, 0.0, 1.0);
```

should compile into, for example,

```
mov ft0.yzw, fc0.yyyz
mov ft0.x, fc1.x
mov oc, ft0
```

where fc0 = 0, 0, 1, 0 (to keep the same constant as currently)

**Comment by graysonlang** [comment]
Yes, I agree. There is something fishy about the compiled output not
matching the intent.

When the desired value for oc is [myConstant, 0, 0, 1] and it is understood
that fc0 = [0, 0, 1, 0]

uniform float myConstant;
void main(void)
{
    gl_FragColor = vec4(myConstant, 0.0, 0.0, 1.0);
}

should yield something along the lines of:

mov ft0.yzw, fc0.yyyz
mov ft0.x, fc1.x
mov oc, ft0

**Comment by alexmac** [comment]
Yep, looks like I've got a bug in my swizzling code, I'll see what I can do to fix it

**Comment by alexmac** [comment]
Should be fixed now
