### ISSUE TITLE
Instruction node present twice in ir tree

### ISSUE THREAD

**Issue by grisevg** [adobe/glsl2agal#18]
I get an error from a compiler when I multiply 2 vec4 with each other. If I do "xyz" multiplication and "w" multiplications separately, there's no error.
Error is:

> Instruction node present twice in ir tree:(expression vec2 + (swiz xy (var_ref fc5) )(swiz xy (var_ref v0) )) 
>      1 [sig] glsl2agalopt 81672 open_stackdumpfile: Dumping stack trace to glsl2agalopt.exe.stackdump
> Result: 34304

Not sure what exactly affecting it, so pasted whole shader code:
This one doesn't work. Line causing error is 29:
http://pastie.org/5822150#29
This one do work:
http://pastie.org/5822153#29-30

Many thanks.

**Comment by alexmac** [comment]
Thanks for the report, looks like a recent injection, but now it is fixed!

**Comment by grisevg** [comment]
Working! Thanks!
