### ISSUE TITLE
the error when i custom code starlingexample

### ISSUE THREAD

**Issue by lizhi525** [adobe/glsl2agal#3]
0(0): error: no matching function for call to `sign()'

**Comment by lizhi525** [comment]
error: register operand 0 (8.y) index exceeds limit of 8.
  at line 0 mov ft8.y, fc0.x

**Comment by alexmac** [comment]
Sometimes the optimizer fails to do a good job allocating temporary registers and you will get that error. Tweaking the GLSL is probably the easiest way of working around that problem, but if you post the full contents of the shader I can have  a look to see if the optimizer could be improved to support it

**Comment by lizhi525** [comment]
the code is this

http://www.gamerendering.com/2008/10/11/gaussian-blur-filter-shader/

**Comment by alexmac** [comment]
Looks like the recent changes have improved register allocation enough to allow the fragment shader to fit within the limits, I've added it as a regression test: tests/regression_000009.fs
