### ISSUE TITLE
?: conditional operator conversion bug

### ISSUE THREAD

**Issue by Antymon** [adobe/glsl2agal#5]
It seems to me that glsl2agal has problem with proper conversion of glsl expressions using ?: operator. Problem is manifested by 'component read without being written to'. I am using swc available at the moment of speaking.

**Comment by alexmac** [comment]
Do you have a simple test case?

**Comment by Antymon** [comment]
I am afraid not. I made a simple test now and everything went fine. I should document the case back then. I guess it is not necessary to treat this as an issue for now.

**Comment by alexmac** [comment]
ok, let me know if you find a shader that fails and I'll re-open the issue
