### ISSUE TITLE
Unable to compile shaders

### ISSUE THREAD

**Issue by deadbeef84** [adobe/glsl2agal#7]
When trying to compile the following fragment shader:

```
varying vec3 vColor;
void main() {
    gl_FragColor = vColor;
}
```

I get the following errors in the info property from the returned JSON object:

```
0:2(20): error: invalid type `vec3' in declaration of `vColor'
0:4(11): error: function `main' has undeclared return type `void'
0:4(11): error: main() must return void
0:5(23): error: `vColor' undeclared
0:5(15): error: type mismatch
0:6(2): error: function `main' has non-void return type (null), but no return statement
```

I'm using the swc from the repository and I'm compiling it using FlashDevelop 4.0.4 (AS3 project, using Flash 11.3 as target). Are there any compiler options needed for this to function properly?

**Comment by Antymon** [comment]
I don't know how this relates to the issue however I do believe that gl_FragColor is a 4 component vector. It appears that your glsl program is malformed in terms of glsl itself - and the behavior of the lib is appropriate (you are kindly informed that sth went wrong). Here is a specification you should follow: http://www.cse.chalmers.se/edu/year/2010/course/TDA361/GLSLangSpec.Full.1.30.08.pdf

**Comment by deadbeef84** [comment]
You're right, however I did declare vColor as `varying vec4 vColor;` to begin with, but then changed it to vec3 when I first got the invalid type `vec4' error.

**Comment by davidejones** [comment]
I have the same problem...

**Comment by alexmac** [comment]
Changing the vec3->vec4 lets it compile for me (using the latest SWC  / example code)

**Comment by tikotus** [comment]
I also have the problem. I'm getting the exact same error message as deadbeef84. Updated to the latest swc, didn't help. Tried targeting different players up to 11.5, didn't help. Tried several shaders, both vertex and fragment, and all give the same errors. Also tried with and without optimizing.

Any ideas? This would be such a great library to have working...

**Comment by alexmac** [comment]
Can you confirm it occurs if you try your shader in the online demo: http://adobe.github.com/glsl2agal/

Can you share your shader?

**Comment by tikotus** [comment]
The shader compiles with the online demo.

Here is the full AS3 code: http://pastebin.com/bVqC8gn0

The trace is:

```
2(21): error: invalid type `vec4' in declaration of `vColor'
3(11): error: function `main' has undeclared return type `void'
3(11): error: main() must return void
5(23): error: `vColor' undeclared
5(15): error: type mismatch
6(2): error: function `main' has non-void return type (null), but no return statement

undefined
```

**Comment by alexmac** [comment]
It looks like you aren't initializing the library, take a look at the simple flex based demo code and you will see that you need to call CModule.startAsync and you probably also want your class to extend ISpecialFile so that you can redirect stdout/stderr somewhere

**Comment by tikotus** [comment]
Thank you! That solved the issue.

**Comment by deadbeef84** [comment]
Yes that solved it for me as well, thanks!
