### ISSUE TITLE
Inverse parser?

### ISSUE THREAD

**Issue by Questium** [adobe/glsl2agal#8]
Is there an inverse parser? Trying to implement the output from this into GLS3D but i need to know if there is an inverse parser? Or will I have to write my self one?

Also in order to compile the standalone converter without the agal optimizer, I needed to add the contrib folder from a fork. Might be interesting to add it to the master branch?

**Comment by alexmac** [comment]
I'm not sure what you mean by an inverse parser, it should be possible to hook this up to GLS3D but I'm not aware of anyone trying that yet.

As for the standalone compiler, I've removed the build options for the version without the agal optimizer as it isn't likely to be useful to anyone
