### ISSUE TITLE
Syntax Error: Unterminated quoted string

### ISSUE THREAD

**Issue by tversteeg** [adobe/glsl2agal#9]
I get the following error when I try to run the command on Linux:

``` unix
./bin/glsl2agalopt -optimize -f input/shader.fs
./bin/glsl2agalopt -optimize -v input/shader.vs

./bin/glsl2agalopt: 1: ./bin/glsl2agalopt: Syntax error: Unterminated quoted string
./bin/glsl2agalopt: 1: ./bin/glsl2agalopt: Syntax error: Unterminated quoted string
```

And I use the sample shaders:

``` GLSL
//shader.fs
varying vec4 vertexColor;
void main()
{
    gl_FragColor = vertexColor;
}
//shader.vs
varying vec4 vertexColor;
void main()
{
    vertexColor = gl_Color;
    gl_Position = ftransform();
}
```

How do I fix this?

**Comment by alexmac** [comment]
Linux isn't supported, only OSX and Windows

**Comment by tversteeg** [comment]
Is there a way that Linux could be supported? I might help if that's possible.

**Comment by alexmac** [comment]
You could compile most of glsl2agal with any native gcc compiler, but the AGAL optimizer is implemented in ActionScript so to merge both the C++ code and the ActionScript I'm using FlasCC, and FlasCC only supports linux.
